language: php

php:
  - 7.4

before_script:
    - composer update
    - cp .env.example .env
    - php artisan key:generate

script:
  - phpunit

deploy:
  provider: heroku
  api_key:
    secure: 9c20096d-f2c3-4338-9805-fd356ba7cfe1