language: php

php:
  - 7.4

before_script:
    - composer update
    - cp .env.example .env
    - php artisan key:generate

script:
  - phpunit

branches:
  only:
    - master
    - dev

deploy:
  provider: heroku
  edge: true
  api_key:
    secure: f494131d-59ce-4ebf-80c1-03794bdc76e9
  app: laravelci